### ISSUE TITLE
Debug=True in production is not cool

### ISSUE THREAD

**Issue by AlexPython** [scaphilo/koalixcrm#112]
http://www.koalix.org/ fails with debug data shown to public.

Oh, man, just do simple:
1. DEBUG = False
2. ALLOWED_HOSTS = [http://www.koalix.org/, anything else you want]

This failure to pay attention to details ruins all the impression.
How can one trust the code written with such a negligence of details?

**Comment by scaphilo** [comment]
Hi Alex

Thanks a lot for sharing your concerns and your impression so openly.

The website koalix.org is currently not in use because we are debating what would be best way to 
promote the application and how we could insure a continues development on the program in future.
The efffect is obviously the worst we can do to support our goal.

best regards
Aaron

**Comment by scaphilo** [comment]
Applied secure settings to the productive environment.
Website is still not available but there is an other ticket taking care of this topic
Thanks again
