### ISSUE TITLE
Translate koalix-crm to Brazilian Portuguese, pt-BR

### ISSUE THREAD

**Issue by scaphilo** [scaphilo/koalixcrm#220]
**Context**
koalix-crm was developed in english as a main language.
As django framework offers a convenient way to translate strings in the admin interface into other languages we can make use of this feature and translate the front-end to other langages.
how the translation is done is described here: https://docs.djangoproject.com/en/2.1/topics/i18n/translation/

**Acceptance Criteria**
The Issue is resolved when the all elements of the django-admin are translated to Portuguese language (crm, accounting, djangoUserExtension and subscriptions)

**Comment by scaphilo** [comment]
Hello Williano

Sorry for my late reply regarding your issue with the fork.
I just saw that you have now your own fork? Are you able to work on your
fork for the moment?
I will need to think about adding you to the developers team when i known
how to set restrictions on the master and on the branches.
As soon as we have worked together for a few weeks this should be no
problem i guess.

best regards
Aaron

Am Mo., 22. Okt. 2018 um 04:09 Uhr schrieb Williano Serpa <
notifications@github.com>:

**Comment by willyudi** [comment]
Hi Aaron, no problem. Now I have solved the issue with fork. I will try to work in translation right now. I will keep you on track.
Thanks and Best Regards,
Williano

**Comment by scaphilo** [comment]
Hello Williano
How is it going?
Do you face any issues where i could help you?
best regards Aaron

**Comment by willyudi** [comment]
Hello Aaron,
I am working on the translate and I have commit some files in my fork(as
you can see in GitHub), I have completed the development environment. Now
the build is working with success in Travis-CI.
But I can't publish the application in Heroku for some reason.
I think next week I can complete the translate activity, because I don`t
have time enough on this days, I am very busy in my job.
Thanks and Best Regards,
Williano

Em sex, 2 de nov de 2018 às 17:54, Aaron Riedener <notifications@github.com>
escreveu:

**Comment by willyudi** [comment]
Great Aaron!! I am very happy with your feedback.
Thanks.
Williano

Em sex, 9 de nov de 2018 às 21:30, Aaron Riedener <notifications@github.com>
escreveu:
